### PR TITLE
Add syntax to generate diagrams in Markdown

### PR DESCRIPTION
**Pull request by melvincwng**
Add Markdown syntax to generate diagrams in GitHub.

PR as part of Hacktoberfest 2022 🥳 💯 🎉

### CODE REVIEW

**Comment by melvincwng** [comment]
PR for resolving issue #20

**Comment by melvincwng** [comment]
Fixed #20

**Comment by melvincwng** [comment]
@atapas Hey Tapas, submitted a PR for your review & approval.

Can you kindly assign this PR to be under me? And add in the 'hacktoberfest' label as well.

Appreciate your speedy review of the PR :)

**Review by atapas — COMMENTED** [review]
@melvincwng 

This is great. I am thinking, how about we add the snippet and examples for the other variants too, TD TB RL? That way it will be one place for people to get all the variants to copy and paste?

Will you add it soon?

**Comment by melvincwng** [comment]
@atapas Let me submit an additional commit :)

Ready in a jiffy 🚤 !

**Comment by atapas** [comment]
@melvincwng Please resolve merge conflcits.

**Comment by melvincwng** [comment]
@atapas Merge conflict resolved, pls kindly review & approve.

**Comment by melvincwng** [comment]
Please kindly add 'hacktoberfest-accepted' label too once approved :)

**Comment by atapas** [comment]
@melvincwng Thanks for adding the other examples so quick!!!!

A small mistake in the merge conflicts I see.. a portion of the footnote example moved below the diagram example. Please correct that

image

**Comment by melvincwng** [comment]
@atapas Hi Tapas, footnotes will always appear at the bottom. Hence the reason why in that image, it's showing at the bottom.

In that case, I will move my section to number 23. While footnotes will be shifted to section 24.

**Comment by melvincwng** [comment]
@atapas , amended my PR.

Please review and check, thanks!

**Review by atapas — APPROVED** [review]
@melvincwng Great job man! Accepting

**Comment by melvincwng** [comment]
@atapas Cheers Tapas, appreciate the speedy review!

Happy HacktoberFest 2022 :D

**Comment by atapas** [comment]
@melvincwng Don't forget to socialize your contribution, great work!

**Pull request merged**
